# Generated by Django 5.0.1 on 2024-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='Our_Mission',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='Our_Vision',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
