# Generated by Django 5.0.1 on 2024-02-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aboutcompany_our_mission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='for_Contact',
        ),
    ]
